// ─────────────────────────────────────────────────────────────────────────────
// Data Source Registry — 100+ sources across all categories
// source_type: 'rss' = direct RSS/Atom fetch | 'web_search' = Gemini grounding
// ─────────────────────────────────────────────────────────────────────────────

export type SourceCategory =
  | 'news_il'       // Israeli news
  | 'news_intl'     // International news
  | 'social'        // Social media & forums
  | 'crypto'        // Crypto news
  | 'macro'         // Macro/central bank data
  | 'commodities'   // Commodities & energy
  | 'geopolitical'  // Geopolitical & defense
  | 'tech'          // Technology & innovation
  | 'regulation'    // Financial regulation
  | 'market_data';  // Market analysis & data

export type SourceType = 'rss' | 'web_search';

export interface DataSource {
  id: string;
  name: string;
  category: SourceCategory;
  url: string;           // RSS URL or descriptive search query
  source_type: SourceType;
  language: 'he' | 'en' | 'ar';
  priority: 1 | 2 | 3;  // 1=highest
}

export const DATA_SOURCES: DataSource[] = [

  // ── ISRAELI NEWS (news_il) ──────────────────────────────────────────────────
  {
    id: 'ynet-econ',
    name: 'Ynet כלכלה',
    category: 'news_il',
    url: 'https://www.ynet.co.il/Integration/StoryRss2.xml',
    source_type: 'rss',
    language: 'he',
    priority: 1,
  },
  {
    id: 'toi-business',
    name: 'Times of Israel Business',
    category: 'news_il',
    url: 'https://www.timesofisrael.com/feed/',
    source_type: 'rss',
    language: 'en',
    priority: 1,
  },
  {
    id: 'jpost-finance',
    name: 'Jerusalem Post Finance',
    category: 'news_il',
    url: 'https://www.jpost.com/rss/rssfeedsfinancial.aspx',
    source_type: 'rss',
    language: 'en',
    priority: 1,
  },
  {
    id: 'globes',
    name: 'גלובס',
    category: 'news_il',
    url: 'https://www.globes.co.il/webservice/rss/rssfeeder.asmx/FeederNode?iID=3',
    source_type: 'rss',
    language: 'he',
    priority: 1,
  },
  {
    id: 'calcalist',
    name: 'כלכליסט',
    category: 'news_il',
    url: 'https://www.calcalist.co.il/rss/',
    source_type: 'rss',
    language: 'he',
    priority: 1,
  },
  {
    id: 'israel-hayom',
    name: 'ישראל היום כלכלה',
    category: 'news_il',
    url: 'https://www.israelhayom.co.il/rss',
    source_type: 'rss',
    language: 'he',
    priority: 2,
  },
  {
    id: 'haaretz-market',
    name: 'הארץ שוק ההון',
    category: 'news_il',
    url: 'https://www.haaretz.co.il/cmlink/1.1614088',
    source_type: 'rss',
    language: 'he',
    priority: 1,
  },
  {
    id: 'themarker',
    name: 'TheMarker',
    category: 'news_il',
    url: 'חדשות כלכליות ישראל TheMarker שוק ההון בורסה תל אביב היום',
    source_type: 'web_search',
    language: 'he',
    priority: 1,
  },
  {
    id: 'walla-finance',
    name: 'וואלה פיננסים',
    category: 'news_il',
    url: 'וואלה פיננסים שוק ההון כלכלה ישראל היום',
    source_type: 'web_search',
    language: 'he',
    priority: 2,
  },
  {
    id: 'mako-economy',
    name: 'מאקו כלכלה',
    category: 'news_il',
    url: 'מאקו כלכלה ישראל שוק ההון בורסה היום',
    source_type: 'web_search',
    language: 'he',
    priority: 2,
  },
  {
    id: 'n12-economy',
    name: 'N12 כלכלה',
    category: 'news_il',
    url: 'N12 חדשות כלכלה שוק ההון ישראל',
    source_type: 'web_search',
    language: 'he',
    priority: 2,
  },
  {
    id: 'channel13-economy',
    name: 'ערוץ 13 כלכלה',
    category: 'news_il',
    url: 'ערוץ 13 חדשות כלכלה ישראל',
    source_type: 'web_search',
    language: 'he',
    priority: 3,
  },
  {
    id: 'reshet-bet',
    name: 'רשת ב כלכלה',
    category: 'news_il',
    url: 'רשת ב רדיו כלכלה ישראל',
    source_type: 'web_search',
    language: 'he',
    priority: 3,
  },
  {
    id: 'kan-economy',
    name: 'כאן כלכלה',
    category: 'news_il',
    url: 'כאן תאגיד השידור כלכלה שוק ישראל',
    source_type: 'web_search',
    language: 'he',
    priority: 3,
  },
  {
    id: 'maariv-economy',
    name: 'מעריב כלכלה',
    category: 'news_il',
    url: 'מעריב כלכלה שוק ישראל היום',
    source_type: 'web_search',
    language: 'he',
    priority: 3,
  },

  // ── INTERNATIONAL NEWS (news_intl) ──────────────────────────────────────────
  {
    id: 'reuters-business',
    name: 'Reuters Business',
    category: 'news_intl',
    url: 'https://feeds.reuters.com/reuters/businessNews',
    source_type: 'rss',
    language: 'en',
    priority: 1,
  },
  {
    id: 'cnbc-top',
    name: 'CNBC Top News',
    category: 'news_intl',
    url: 'https://www.cnbc.com/id/100003114/device/rss/rss.html',
    source_type: 'rss',
    language: 'en',
    priority: 1,
  },
  {
    id: 'bbc-business',
    name: 'BBC Business',
    category: 'news_intl',
    url: 'http://feeds.bbci.co.uk/news/business/rss.xml',
    source_type: 'rss',
    language: 'en',
    priority: 1,
  },
  {
    id: 'guardian-business',
    name: 'The Guardian Business',
    category: 'news_intl',
    url: 'https://www.theguardian.com/business/rss',
    source_type: 'rss',
    language: 'en',
    priority: 1,
  },
  {
    id: 'nyt-business',
    name: 'New York Times Business',
    category: 'news_intl',
    url: 'https://rss.nytimes.com/services/xml/rss/nyt/Business.xml',
    source_type: 'rss',
    language: 'en',
    priority: 1,
  },
  {
    id: 'marketwatch',
    name: 'MarketWatch',
    category: 'news_intl',
    url: 'http://feeds.marketwatch.com/marketwatch/topstories/',
    source_type: 'rss',
    language: 'en',
    priority: 1,
  },
  {
    id: 'seeking-alpha',
    name: 'Seeking Alpha',
    category: 'news_intl',
    url: 'https://seekingalpha.com/feed.xml',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'economist-finance',
    name: 'The Economist Finance',
    category: 'news_intl',
    url: 'https://www.economist.com/finance-and-economics/rss.xml',
    source_type: 'rss',
    language: 'en',
    priority: 1,
  },
  {
    id: 'politico-economy',
    name: 'Politico Economy',
    category: 'news_intl',
    url: 'https://www.politico.com/rss/economy.xml',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'bloomberg-markets',
    name: 'Bloomberg Markets',
    category: 'news_intl',
    url: 'Bloomberg markets finance news today latest',
    source_type: 'web_search',
    language: 'en',
    priority: 1,
  },
  {
    id: 'wsj-markets',
    name: 'Wall Street Journal Markets',
    category: 'news_intl',
    url: 'Wall Street Journal markets stocks bonds today',
    source_type: 'web_search',
    language: 'en',
    priority: 1,
  },
  {
    id: 'ft-markets',
    name: 'Financial Times',
    category: 'news_intl',
    url: 'Financial Times markets economy latest news today',
    source_type: 'web_search',
    language: 'en',
    priority: 1,
  },
  {
    id: 'forbes',
    name: 'Forbes Markets',
    category: 'news_intl',
    url: 'https://www.forbes.com/real-time/feed2/',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'business-insider',
    name: 'Business Insider',
    category: 'news_intl',
    url: 'https://feeds.businessinsider.com/custom/all',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'ap-business',
    name: 'AP Business',
    category: 'news_intl',
    url: 'https://apnews.com/hub/business.rss',
    source_type: 'rss',
    language: 'en',
    priority: 1,
  },
  {
    id: 'barrons',
    name: "Barron's",
    category: 'news_intl',
    url: "Barron's stocks markets analysis today",
    source_type: 'web_search',
    language: 'en',
    priority: 2,
  },
  {
    id: 'prnewswire',
    name: 'PR Newswire Financial',
    category: 'news_intl',
    url: 'https://www.prnewswire.com/rss/news-releases-list.rss',
    source_type: 'rss',
    language: 'en',
    priority: 3,
  },

  // ── SOCIAL MEDIA (social) ───────────────────────────────────────────────────
  {
    id: 'trump-x',
    name: 'Trump X/Twitter',
    category: 'social',
    url: 'Trump Twitter X statements economy markets tariffs today',
    source_type: 'web_search',
    language: 'en',
    priority: 1,
  },
  {
    id: 'fed-powell-x',
    name: 'Fed Powell Statements',
    category: 'social',
    url: 'Federal Reserve Powell statement speech interest rates economy today',
    source_type: 'web_search',
    language: 'en',
    priority: 1,
  },
  {
    id: 'israel-pm-x',
    name: 'Israeli PM Statements',
    category: 'social',
    url: 'Netanyahu statements Israel economy markets Twitter X today',
    source_type: 'web_search',
    language: 'he',
    priority: 1,
  },
  {
    id: 'reddit-investing',
    name: 'Reddit r/investing',
    category: 'social',
    url: 'https://www.reddit.com/r/investing/.rss',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'reddit-wsb',
    name: 'Reddit WallStreetBets',
    category: 'social',
    url: 'https://www.reddit.com/r/wallstreetbets/.rss',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'reddit-stocks',
    name: 'Reddit r/stocks',
    category: 'social',
    url: 'https://www.reddit.com/r/stocks/.rss',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'reddit-economics',
    name: 'Reddit r/economics',
    category: 'social',
    url: 'https://www.reddit.com/r/economics/.rss',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'reddit-geopolitics',
    name: 'Reddit r/geopolitics',
    category: 'social',
    url: 'https://www.reddit.com/r/geopolitics/.rss',
    source_type: 'rss',
    language: 'en',
    priority: 3,
  },
  {
    id: 'stocktwits-trending',
    name: 'StockTwits Trending',
    category: 'social',
    url: 'StockTwits trending stocks mentions sentiment today',
    source_type: 'web_search',
    language: 'en',
    priority: 2,
  },
  {
    id: 'twitter-finance-trending',
    name: 'Twitter Finance Trending',
    category: 'social',
    url: 'Twitter X trending finance stocks investing today most discussed',
    source_type: 'web_search',
    language: 'en',
    priority: 2,
  },
  {
    id: 'elon-musk-x',
    name: 'Elon Musk X Statements',
    category: 'social',
    url: 'Elon Musk Twitter X statements markets DOGE economy today',
    source_type: 'web_search',
    language: 'en',
    priority: 2,
  },
  {
    id: 'us-treasury-secretary',
    name: 'US Treasury Secretary Statements',
    category: 'social',
    url: 'US Treasury Secretary Bessent statements economy markets today',
    source_type: 'web_search',
    language: 'en',
    priority: 1,
  },

  // ── CRYPTO (crypto) ─────────────────────────────────────────────────────────
  {
    id: 'coindesk',
    name: 'CoinDesk',
    category: 'crypto',
    url: 'https://www.coindesk.com/arc/outboundfeeds/rss/',
    source_type: 'rss',
    language: 'en',
    priority: 1,
  },
  {
    id: 'cointelegraph',
    name: 'CoinTelegraph',
    category: 'crypto',
    url: 'https://cointelegraph.com/rss',
    source_type: 'rss',
    language: 'en',
    priority: 1,
  },
  {
    id: 'decrypt',
    name: 'Decrypt',
    category: 'crypto',
    url: 'https://decrypt.co/feed',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'cryptoslate',
    name: 'CryptoSlate',
    category: 'crypto',
    url: 'https://cryptoslate.com/feed/',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'bitcoin-magazine',
    name: 'Bitcoin Magazine',
    category: 'crypto',
    url: 'https://bitcoinmagazine.com/.rss/full/',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'the-block',
    name: 'The Block',
    category: 'crypto',
    url: 'https://www.theblock.co/rss.xml',
    source_type: 'rss',
    language: 'en',
    priority: 1,
  },
  {
    id: 'coinmarketcap-news',
    name: 'CoinMarketCap News',
    category: 'crypto',
    url: 'CoinMarketCap cryptocurrency news Bitcoin Ethereum today',
    source_type: 'web_search',
    language: 'en',
    priority: 2,
  },
  {
    id: 'binance-news',
    name: 'Binance News',
    category: 'crypto',
    url: 'Binance exchange news Bitcoin crypto market today',
    source_type: 'web_search',
    language: 'en',
    priority: 2,
  },
  {
    id: 'crypto-social-buzz',
    name: 'Crypto Social Buzz',
    category: 'crypto',
    url: 'Bitcoin Ethereum crypto Twitter Reddit trending discussions today',
    source_type: 'web_search',
    language: 'en',
    priority: 2,
  },

  // ── MACRO / CENTRAL BANKS (macro) ───────────────────────────────────────────
  {
    id: 'fed-press',
    name: 'Federal Reserve Press Releases',
    category: 'macro',
    url: 'https://www.federalreserve.gov/feeds/press_monetary.xml',
    source_type: 'rss',
    language: 'en',
    priority: 1,
  },
  {
    id: 'us-treasury-news',
    name: 'US Treasury News',
    category: 'macro',
    url: 'https://home.treasury.gov/news/rss.xml',
    source_type: 'rss',
    language: 'en',
    priority: 1,
  },
  {
    id: 'imf-blog',
    name: 'IMF Blog',
    category: 'macro',
    url: 'https://www.imf.org/en/Blogs/rss',
    source_type: 'rss',
    language: 'en',
    priority: 1,
  },
  {
    id: 'world-bank',
    name: 'World Bank News',
    category: 'macro',
    url: 'https://feeds.worldbank.org/worldbank/finances/rss.xml',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'oecd-news',
    name: 'OECD News',
    category: 'macro',
    url: 'https://www.oecd.org/newsroom/rss.xml',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'bis-news',
    name: 'BIS (Bank for International Settlements)',
    category: 'macro',
    url: 'https://www.bis.org/rss/index.htm',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'bank-of-england',
    name: 'Bank of England',
    category: 'macro',
    url: 'https://www.bankofengland.co.uk/rss/news',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'ecb-press',
    name: 'ECB Press Releases',
    category: 'macro',
    url: 'European Central Bank ECB press release interest rates decision today',
    source_type: 'web_search',
    language: 'en',
    priority: 1,
  },
  {
    id: 'bank-of-israel',
    name: 'Bank of Israel',
    category: 'macro',
    url: 'בנק ישראל ריבית הודעה מדיניות מוניטרית היום',
    source_type: 'web_search',
    language: 'he',
    priority: 1,
  },
  {
    id: 'us-cpi-ppi',
    name: 'US CPI/PPI Data',
    category: 'macro',
    url: 'US CPI PPI inflation data BLS Bureau of Labor Statistics latest report',
    source_type: 'web_search',
    language: 'en',
    priority: 1,
  },
  {
    id: 'us-jobs-data',
    name: 'US Jobs Data',
    category: 'macro',
    url: 'US jobs unemployment non-farm payroll report today latest',
    source_type: 'web_search',
    language: 'en',
    priority: 1,
  },
  {
    id: 'us-gdp-data',
    name: 'US GDP Data',
    category: 'macro',
    url: 'US GDP economic growth BEA report latest quarter',
    source_type: 'web_search',
    language: 'en',
    priority: 2,
  },
  {
    id: 'china-pboc',
    name: "People's Bank of China",
    category: 'macro',
    url: "People's Bank of China PBOC policy rates economy today",
    source_type: 'web_search',
    language: 'en',
    priority: 2,
  },
  {
    id: 'boj',
    name: 'Bank of Japan',
    category: 'macro',
    url: 'Bank of Japan BOJ interest rates yen policy today',
    source_type: 'web_search',
    language: 'en',
    priority: 2,
  },

  // ── COMMODITIES (commodities) ───────────────────────────────────────────────
  {
    id: 'oilprice',
    name: 'OilPrice.com',
    category: 'commodities',
    url: 'https://oilprice.com/rss/main',
    source_type: 'rss',
    language: 'en',
    priority: 1,
  },
  {
    id: 'kitco-gold',
    name: 'Kitco Gold',
    category: 'commodities',
    url: 'https://www.kitco.com/rss/',
    source_type: 'rss',
    language: 'en',
    priority: 1,
  },
  {
    id: 'eia-energy',
    name: 'EIA Energy News',
    category: 'commodities',
    url: 'https://www.eia.gov/rss/news.xml',
    source_type: 'rss',
    language: 'en',
    priority: 1,
  },
  {
    id: 'gold-price-today',
    name: 'Gold Price Today',
    category: 'commodities',
    url: 'gold price today market movement news',
    source_type: 'web_search',
    language: 'en',
    priority: 1,
  },
  {
    id: 'oil-crude-today',
    name: 'Crude Oil Today',
    category: 'commodities',
    url: 'crude oil WTI Brent price today OPEC news',
    source_type: 'web_search',
    language: 'en',
    priority: 1,
  },
  {
    id: 'natural-gas',
    name: 'Natural Gas Market',
    category: 'commodities',
    url: 'natural gas price market news today',
    source_type: 'web_search',
    language: 'en',
    priority: 2,
  },
  {
    id: 'silver-copper',
    name: 'Silver & Copper',
    category: 'commodities',
    url: 'silver copper commodities price market today',
    source_type: 'web_search',
    language: 'en',
    priority: 3,
  },
  {
    id: 'opec-news',
    name: 'OPEC News',
    category: 'commodities',
    url: 'OPEC oil production decision meeting news today',
    source_type: 'web_search',
    language: 'en',
    priority: 1,
  },

  // ── GEOPOLITICAL (geopolitical) ─────────────────────────────────────────────
  {
    id: 'aljazeera',
    name: 'Al Jazeera',
    category: 'geopolitical',
    url: 'https://www.aljazeera.com/xml/rss/all.xml',
    source_type: 'rss',
    language: 'en',
    priority: 1,
  },
  {
    id: 'middle-east-eye',
    name: 'Middle East Eye',
    category: 'geopolitical',
    url: 'https://www.middleeasteye.net/rss',
    source_type: 'rss',
    language: 'en',
    priority: 1,
  },
  {
    id: 'foreign-policy',
    name: 'Foreign Policy',
    category: 'geopolitical',
    url: 'https://foreignpolicy.com/feed/',
    source_type: 'rss',
    language: 'en',
    priority: 1,
  },
  {
    id: 'breaking-defense',
    name: 'Breaking Defense',
    category: 'geopolitical',
    url: 'https://breakingdefense.com/feed/',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'defense-news',
    name: 'Defense News',
    category: 'geopolitical',
    url: 'https://www.defensenews.com/arc/outboundfeeds/rss/',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'cfr-news',
    name: 'Council on Foreign Relations',
    category: 'geopolitical',
    url: 'https://www.cfr.org/feeds/blog_posts',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'iran-intl',
    name: 'Iran International',
    category: 'geopolitical',
    url: 'Iran International news nuclear military today',
    source_type: 'web_search',
    language: 'en',
    priority: 1,
  },
  {
    id: 'israel-war-news',
    name: 'Israel War/Security News',
    category: 'geopolitical',
    url: 'Israel Gaza Hamas war ceasefire security today latest',
    source_type: 'web_search',
    language: 'en',
    priority: 1,
  },
  {
    id: 'russia-ukraine',
    name: 'Russia-Ukraine War',
    category: 'geopolitical',
    url: 'Russia Ukraine war ceasefire sanctions news today latest',
    source_type: 'web_search',
    language: 'en',
    priority: 1,
  },
  {
    id: 'china-taiwan',
    name: 'China-Taiwan Tensions',
    category: 'geopolitical',
    url: 'China Taiwan tension military news today latest',
    source_type: 'web_search',
    language: 'en',
    priority: 2,
  },
  {
    id: 'us-sanctions',
    name: 'US Sanctions & Trade',
    category: 'geopolitical',
    url: 'US sanctions tariffs trade war China today latest',
    source_type: 'web_search',
    language: 'en',
    priority: 1,
  },
  {
    id: 'nato-news',
    name: 'NATO News',
    category: 'geopolitical',
    url: 'NATO news defense alliance military today',
    source_type: 'web_search',
    language: 'en',
    priority: 2,
  },

  // ── TECHNOLOGY (tech) ───────────────────────────────────────────────────────
  {
    id: 'techcrunch',
    name: 'TechCrunch',
    category: 'tech',
    url: 'https://techcrunch.com/feed/',
    source_type: 'rss',
    language: 'en',
    priority: 1,
  },
  {
    id: 'wired',
    name: 'Wired',
    category: 'tech',
    url: 'https://www.wired.com/feed/rss',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'mit-tech-review',
    name: 'MIT Technology Review',
    category: 'tech',
    url: 'https://www.technologyreview.com/feed/',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'venturebeat',
    name: 'VentureBeat',
    category: 'tech',
    url: 'https://venturebeat.com/feed/',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'ars-technica',
    name: 'Ars Technica',
    category: 'tech',
    url: 'https://feeds.arstechnica.com/arstechnica/index',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'the-verge',
    name: 'The Verge',
    category: 'tech',
    url: 'https://www.theverge.com/rss/index.xml',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'ai-news',
    name: 'AI Industry News',
    category: 'tech',
    url: 'artificial intelligence AI OpenAI Google Microsoft tech news today',
    source_type: 'web_search',
    language: 'en',
    priority: 2,
  },
  {
    id: 'big-tech-earnings',
    name: 'Big Tech Earnings',
    category: 'tech',
    url: 'Apple Google Microsoft Meta Amazon earnings results stock today',
    source_type: 'web_search',
    language: 'en',
    priority: 1,
  },
  {
    id: 'semiconductor-news',
    name: 'Semiconductor Industry',
    category: 'tech',
    url: 'semiconductor chip Nvidia AMD Intel industry news today',
    source_type: 'web_search',
    language: 'en',
    priority: 2,
  },

  // ── FINANCIAL REGULATION (regulation) ───────────────────────────────────────
  {
    id: 'sec-news',
    name: 'SEC Press Releases',
    category: 'regulation',
    url: 'SEC Securities Exchange Commission press release enforcement today',
    source_type: 'web_search',
    language: 'en',
    priority: 2,
  },
  {
    id: 'cftc-news',
    name: 'CFTC News',
    category: 'regulation',
    url: 'https://www.cftc.gov/rss/pressreleases.xml',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'fca-news',
    name: 'FCA UK News',
    category: 'regulation',
    url: 'https://www.fca.org.uk/news/rss.xml',
    source_type: 'rss',
    language: 'en',
    priority: 3,
  },
  {
    id: 'crypto-regulation',
    name: 'Crypto Regulation News',
    category: 'regulation',
    url: 'cryptocurrency Bitcoin regulation SEC CFTC law news today',
    source_type: 'web_search',
    language: 'en',
    priority: 2,
  },
  {
    id: 'israel-isa',
    name: 'Israel Securities Authority',
    category: 'regulation',
    url: 'רשות ניירות ערך ישראל רגולציה שוק הון היום',
    source_type: 'web_search',
    language: 'he',
    priority: 2,
  },

  // ── MARKET DATA & ANALYSIS (market_data) ────────────────────────────────────
  {
    id: 'motley-fool',
    name: 'Motley Fool',
    category: 'market_data',
    url: 'https://www.fool.com/feeds/index.aspx',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'investorplace',
    name: 'InvestorPlace',
    category: 'market_data',
    url: 'https://investorplace.com/feed/',
    source_type: 'rss',
    language: 'en',
    priority: 2,
  },
  {
    id: 'globenewswire',
    name: 'GlobeNewswire Financial',
    category: 'market_data',
    url: 'https://www.globenewswire.com/RssFeed/subjectcode/15-Financial%20Markets',
    source_type: 'rss',
    language: 'en',
    priority: 3,
  },
  {
    id: 'vix-fear-index',
    name: 'VIX Fear Index',
    category: 'market_data',
    url: 'VIX fear index CBOE volatility market today level',
    source_type: 'web_search',
    language: 'en',
    priority: 1,
  },
  {
    id: 'sp500-sector-rotation',
    name: 'S&P 500 Sector Rotation',
    category: 'market_data',
    url: 'S&P 500 sector rotation leading lagging sectors performance today',
    source_type: 'web_search',
    language: 'en',
    priority: 2,
  },
  {
    id: 'analyst-upgrades',
    name: 'Analyst Upgrades/Downgrades',
    category: 'market_data',
    url: 'stock analyst upgrade downgrade price target change today',
    source_type: 'web_search',
    language: 'en',
    priority: 2,
  },
  {
    id: 'earnings-calendar',
    name: 'Earnings Calendar',
    category: 'market_data',
    url: 'earnings calendar upcoming reports results this week stocks',
    source_type: 'web_search',
    language: 'en',
    priority: 2,
  },
  {
    id: 'hedge-fund-activity',
    name: 'Hedge Fund Activity',
    category: 'market_data',
    url: 'hedge fund 13F filing positions buying selling stocks today',
    source_type: 'web_search',
    language: 'en',
    priority: 2,
  },
  {
    id: 'options-flow',
    name: 'Options Flow',
    category: 'market_data',
    url: 'unusual options activity flow dark pool trades today',
    source_type: 'web_search',
    language: 'en',
    priority: 2,
  },
  {
    id: 'short-interest',
    name: 'Short Interest',
    category: 'market_data',
    url: 'most shorted stocks short interest squeeze today',
    source_type: 'web_search',
    language: 'en',
    priority: 3,
  },
  {
    id: 'insider-trading',
    name: 'Insider Trading',
    category: 'market_data',
    url: 'insider trading SEC Form 4 executives buying selling shares today',
    source_type: 'web_search',
    language: 'en',
    priority: 2,
  },
  {
    id: 'ipo-spac',
    name: 'IPO & SPAC News',
    category: 'market_data',
    url: 'IPO SPAC new listings stock market this week',
    source_type: 'web_search',
    language: 'en',
    priority: 3,
  },
  {
    id: 'bonds-yields',
    name: 'Bond Yields & Treasuries',
    category: 'market_data',
    url: 'US Treasury yields bonds 10-year 2-year yield curve today',
    source_type: 'web_search',
    language: 'en',
    priority: 1,
  },
  {
    id: 'dollar-index',
    name: 'Dollar Index (DXY)',
    category: 'market_data',
    url: 'US dollar DXY index currency forex markets today',
    source_type: 'web_search',
    language: 'en',
    priority: 1,
  },
  {
    id: 'israel-shekel',
    name: 'Israeli Shekel Rate',
    category: 'market_data',
    url: 'שער דולר שקל ישראלי ביחס למטבעות שוק המט"ח היום',
    source_type: 'web_search',
    language: 'he',
    priority: 1,
  },
  {
    id: 'taavura-ta35',
    name: 'TA-35 Index',
    category: 'market_data',
    url: 'מדד תל אביב 35 בורסה ישראל ביצועים היום',
    source_type: 'web_search',
    language: 'he',
    priority: 1,
  },
];

// Helper: get all sources by category
export function getSourcesByCategory(category: SourceCategory): DataSource[] {
  return DATA_SOURCES.filter(s => s.category === category);
}

// Helper: get all RSS sources
export function getRSSSources(): DataSource[] {
  return DATA_SOURCES.filter(s => s.source_type === 'rss');
}

// Helper: get all web search sources grouped by category for batching
export function getWebSearchSourcesByCategory(): Map<SourceCategory, DataSource[]> {
  const map = new Map<SourceCategory, DataSource[]>();
  for (const source of DATA_SOURCES.filter(s => s.source_type === 'web_search')) {
    const existing = map.get(source.category) ?? [];
    existing.push(source);
    map.set(source.category, existing);
  }
  return map;
}

// Total count for validation
export const TOTAL_SOURCES = DATA_SOURCES.length;
